# Configuration schema for the CAS module

cas.settings:
  type: mapping
  label: 'CAS settings'
  mapping:
    server:
      type: mapping
      label: 'CAS Server'
      mapping:
        version:
          type: string
          label: 'Version'
        hostname:
          type: string
          label: 'Hostname'
        port:
          type: integer
          label: 'Port'
        path:
          type: string
          label: 'Path'
        cert:
          type: string
          label: 'PEM Cert path'
    gateway:
      type: mapping
      label: 'Gateway Feature'
      mapping:
        check_frequency:
          type: integer
          label: 'Check Frequency'
        paths:
          type: condition.plugin.request_path
          label: 'Paths'
    forced_login:
      type: mapping
      label: 'Forced Login'
      mapping:
        enabled:
          type: boolean
          label: 'Enable'
        paths:
          type: condition.plugin.request_path
          label: 'Paths'
    user_accounts:
      type: mapping
      label: 'User Accounts'
      mapping:
        auto_register:
          type: boolean
          label: 'Auto Register Users'
